[project]
name = "transcription"
version = "0.1.0"
description="Converts Speech to Text"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "faster-whisper",
  "modal",
  "fastapi",
  "python-multipart",
]